# Generated by Django 3.0.5 on 2021-11-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsitem_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
