# Generated by Django 3.0.5 on 2021-11-30 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scrapehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapehistory',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapehistory',
            name='finished_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
