# Generated by Django 3.0.5 on 2023-04-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230402_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='published_date',
            field=models.DateField(),
        ),
    ]
